# Generated by Django 3.1.7 on 2021-02-24 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_auto_20210223_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='currentlocation',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='fromlocation',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='imageurl',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='videourl',
            field=models.URLField(),
        ),
    ]
