# Generated by Django 3.1.7 on 2021-02-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20210224_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imageurl',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='videourl',
            field=models.URLField(blank=True),
        ),
    ]
