# Generated by Django 3.1.7 on 2021-02-24 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_post_datetime'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Follower',
            new_name='Follow',
        ),
    ]
