# Generated by Django 3.1.7 on 2021-03-01 13:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_auto_20210224_1804'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['datetime']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['datetime']},
        ),
        migrations.AddField(
            model_name='comment',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
